"""initial maintenance schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-14
"""
from alembic import op
import sqlalchemy as sa


revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_role'), 'audit_logs', ['role'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purl', sa.Text(), nullable=False),
    sa.Column('ecosystem', sa.String(length=100), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('cpe', sa.Text(), nullable=True),
    sa.Column('hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_ecosystem'), 'components', ['ecosystem'], unique=False)
    op.create_index(op.f('ix_components_name'), 'components', ['name'], unique=False)
    op.create_index(op.f('ix_components_purl'), 'components', ['purl'], unique=True)
    op.create_index(op.f('ix_components_version'), 'components', ['version'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', 'unknown', name='severity'), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('github', 'manual', 'local', 'isolated', name='repositoryprovider'), nullable=False),
    sa.Column('provider_repository_id', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=True),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('fork', sa.Boolean(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('primary_language', sa.String(length=100), nullable=True),
    sa.Column('source_classification', sa.Enum('public', 'private', 'restricted', 'isolated', name='sourceclassification'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'owner', 'name', name='uq_repository_provider_owner_name'),
    sa.UniqueConstraint('provider', 'provider_repository_id', name='uq_repository_provider_id')
    )
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=False)
    op.create_index(op.f('ix_repositories_owner'), 'repositories', ['owner'], unique=False)
    op.create_index(op.f('ix_repositories_provider'), 'repositories', ['provider'], unique=False)
    op.create_index(op.f('ix_repositories_provider_repository_id'), 'repositories', ['provider_repository_id'], unique=False)
    op.create_index(op.f('ix_repositories_source_classification'), 'repositories', ['source_classification'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', 'unknown', name='severity'), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_vulnerability_source_external_id')
    )
    op.create_index(op.f('ix_vulnerabilities_external_id'), 'vulnerabilities', ['external_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_severity'), 'vulnerabilities', ['severity'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_source'), 'vulnerabilities', ['source'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('application_type', sa.Enum('web', 'api', 'batch', 'cli', 'browser_extension', 'desktop', 'library', 'container', 'serverless', 'security_research', 'unknown', name='applicationtype'), nullable=False),
    sa.Column('lifecycle', sa.Enum('experimental', 'active', 'maintenance', 'deprecated', 'archived', 'research', name='lifecycle'), nullable=False),
    sa.Column('criticality', sa.String(length=50), nullable=False),
    sa.Column('internet_exposed', sa.Boolean(), nullable=False),
    sa.Column('production', sa.Boolean(), nullable=False),
    sa.Column('auto_fix_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_merge_enabled', sa.Boolean(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('support_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'path', name='uq_application_repository_path')
    )
    op.create_index(op.f('ix_applications_name'), 'applications', ['name'], unique=False)
    op.create_index(op.f('ix_applications_repository_id'), 'applications', ['repository_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('repository_sync', 'scan', 'remediation_validation', 'issue_create', 'notification', 'ai_fix', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', 'timed_out', name='jobstatus'), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(length=255), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_application_id'), 'jobs', ['application_id'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index('ix_jobs_queue', 'jobs', ['status', 'run_after', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_repository_id'), 'jobs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_jobs_run_after'), 'jobs', ['run_after'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('scan_type', sa.String(length=100), nullable=False),
    sa.Column('trigger_type', sa.Enum('initial_import', 'pull_request', 'push', 'release', 'schedule', 'advisory_update', 'manual', 'remediation_validation', name='triggertype'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'partially_succeeded', 'failed', 'cancelled', 'timed_out', name='scanstatus'), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('tool', sa.String(length=100), nullable=True),
    sa.Column('tool_version', sa.String(length=100), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_application_id'), 'scans', ['application_id'], unique=False)
    op.create_index(op.f('ix_scans_commit_sha'), 'scans', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_scans_created_at'), 'scans', ['created_at'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('technologies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('detection_source', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technologies_application_id'), 'technologies', ['application_id'], unique=False)
    op.create_index(op.f('ix_technologies_category'), 'technologies', ['category'], unique=False)
    op.create_index(op.f('ix_technologies_name'), 'technologies', ['name'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('vulnerability_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('open', 'triaged', 'in_progress', 'resolved', 'accepted_risk', 'false_positive', name='findingstatus'), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', 'unknown', name='severity'), nullable=False),
    sa.Column('first_seen_scan_id', sa.UUID(), nullable=True),
    sa.Column('last_seen_scan_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fixed_version', sa.String(length=255), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['first_seen_scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['last_seen_scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'component_id', 'vulnerability_id', name='uq_finding_identity')
    )
    op.create_index(op.f('ix_findings_application_id'), 'findings', ['application_id'], unique=False)
    op.create_index(op.f('ix_findings_component_id'), 'findings', ['component_id'], unique=False)
    op.create_index(op.f('ix_findings_created_at'), 'findings', ['created_at'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_index(op.f('ix_findings_vulnerability_id'), 'findings', ['vulnerability_id'], unique=False)
    op.create_table('sboms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('sbom_kind', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=100), nullable=False),
    sa.Column('specification_version', sa.String(length=50), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('artifact_digest', sa.String(length=128), nullable=True),
    sa.Column('sbom_digest', sa.String(length=128), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sboms_active'), 'sboms', ['active'], unique=False)
    op.create_index(op.f('ix_sboms_application_id'), 'sboms', ['application_id'], unique=False)
    op.create_index(op.f('ix_sboms_sbom_digest'), 'sboms', ['sbom_digest'], unique=False)
    op.create_index(op.f('ix_sboms_scan_id'), 'sboms', ['scan_id'], unique=False)
    op.create_table('remediation_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('fixed_version', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_actions_action_type'), 'remediation_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_remediation_actions_finding_id'), 'remediation_actions', ['finding_id'], unique=False)
    op.create_index(op.f('ix_remediation_actions_status'), 'remediation_actions', ['status'], unique=False)
    op.create_table('sbom_components',
    sa.Column('sbom_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['sbom_id'], ['sboms.id'], ),
    sa.PrimaryKeyConstraint('sbom_id', 'component_id')
    )
    op.create_table('vex_statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('not_affected', 'affected', 'fixed', 'under_investigation', name='vexstatus'), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('impact_statement', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vex_statements_finding_id'), 'vex_statements', ['finding_id'], unique=False)
    op.create_index(op.f('ix_vex_statements_review_date'), 'vex_statements', ['review_date'], unique=False)
    op.create_index(op.f('ix_vex_statements_status'), 'vex_statements', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vex_statements_status'), table_name='vex_statements')
    op.drop_index(op.f('ix_vex_statements_review_date'), table_name='vex_statements')
    op.drop_index(op.f('ix_vex_statements_finding_id'), table_name='vex_statements')
    op.drop_table('vex_statements')
    op.drop_table('sbom_components')
    op.drop_index(op.f('ix_remediation_actions_status'), table_name='remediation_actions')
    op.drop_index(op.f('ix_remediation_actions_finding_id'), table_name='remediation_actions')
    op.drop_index(op.f('ix_remediation_actions_action_type'), table_name='remediation_actions')
    op.drop_table('remediation_actions')
    op.drop_index(op.f('ix_sboms_scan_id'), table_name='sboms')
    op.drop_index(op.f('ix_sboms_sbom_digest'), table_name='sboms')
    op.drop_index(op.f('ix_sboms_application_id'), table_name='sboms')
    op.drop_index(op.f('ix_sboms_active'), table_name='sboms')
    op.drop_table('sboms')
    op.drop_index(op.f('ix_findings_vulnerability_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_created_at'), table_name='findings')
    op.drop_index(op.f('ix_findings_component_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_application_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_technologies_name'), table_name='technologies')
    op.drop_index(op.f('ix_technologies_category'), table_name='technologies')
    op.drop_index(op.f('ix_technologies_application_id'), table_name='technologies')
    op.drop_table('technologies')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_created_at'), table_name='scans')
    op.drop_index(op.f('ix_scans_commit_sha'), table_name='scans')
    op.drop_index(op.f('ix_scans_application_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_run_after'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_repository_id'), table_name='jobs')
    op.drop_index('ix_jobs_queue', table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_application_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_applications_repository_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_name'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_vulnerabilities_source'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_severity'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_external_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_repositories_source_classification'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_provider_repository_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_provider'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_owner'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_components_version'), table_name='components')
    op.drop_index(op.f('ix_components_purl'), table_name='components')
    op.drop_index(op.f('ix_components_name'), table_name='components')
    op.drop_index(op.f('ix_components_ecosystem'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_audit_logs_role'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###

    # autogenerate does not drop the enum types it creates for sa.Enum columns;
    # without this, a downgrade-then-upgrade cycle fails with "type already exists".
    for enum_name in (
        "vexstatus",
        "findingstatus",
        "scanstatus",
        "triggertype",
        "jobstatus",
        "jobtype",
        "lifecycle",
        "applicationtype",
        "sourceclassification",
        "repositoryprovider",
        "severity",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

